<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<ApplicationIcon>favicon.ico</ApplicationIcon>
		<Version>1.2.0</Version>
		<AssemblyVersion>1.2.0</AssemblyVersion>
		<FileVersion>1.2.0</FileVersion>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="favicon.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="InputSimulator" Version="1.0.4" />
		<PackageReference Include="MaterialDesignColors" Version="5.3.2" />
		<PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
		<PackageReference Include="Octokit" Version="14.0.0" />
		<PackageReference Include="System.Text.Json" Version="11.0.0-preview.4.26230.115" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="favicon.ico" />
	</ItemGroup>
	

</Project>
